/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import seguridad.datos.Asignacion_UsuarioDAO;
import seguridad.dominio.Asignacion_Usuario;

/**
 *
 * @author Gerson
 */
public class Asignacion_A_Usuarios extends javax.swing.JInternalFrame {
DefaultListModel list = new DefaultListModel();
 DefaultListModel list1 = new DefaultListModel();
    /**
     * Creates new form Asignacion_A_Usuarios
     */
    public Asignacion_A_Usuarios() {
        initComponents();
        Asignacion_UsuarioDAO usuarioDAO = new Asignacion_UsuarioDAO();
        List<Asignacion_Usuario> usuario = usuarioDAO.select();

        for (Asignacion_Usuario persona : usuario) {
           System.out.println("persona:" + persona);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cod_Usuario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btn_todos_perfiles_a_Aplicaciones = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btn_Quitar_uno = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_Perfiles_A_Aplicaciones = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_Quitar_Todos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Asignación a Usuarios");
        setVisible(true);

        txt_cod_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_UsuarioActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Aplicaciones Disponibles");

        btn_todos_perfiles_a_Aplicaciones.setText(">>");
        btn_todos_perfiles_a_Aplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todos_perfiles_a_AplicacionesActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        btn_Quitar_uno.setText("<");
        btn_Quitar_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_unoActionPerformed(evt);
            }
        });

        jLabel5.setText("Quitar");

        btn_Perfiles_A_Aplicaciones.setText(">");
        btn_Perfiles_A_Aplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Perfiles_A_AplicacionesActionPerformed(evt);
            }
        });

        jLabel6.setText("asignar");

        jLabel1.setText("aplicaciones asignadas");

        btn_Quitar_Todos.setText("<<");
        btn_Quitar_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_TodosActionPerformed(evt);
            }
        });

        jButton1.setText("editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_cod_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_Perfiles_A_Aplicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_todos_perfiles_a_Aplicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Quitar_uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5))
                        .addComponent(jLabel6)
                        .addComponent(btn_Quitar_Todos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cod_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_guardar))
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Perfiles_A_Aplicaciones)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_todos_perfiles_a_Aplicaciones)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Quitar_uno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Quitar_Todos))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_todos_perfiles_a_AplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todos_perfiles_a_AplicacionesActionPerformed
        ListModel modelo1= jList1.getModel();// listModel es un objeto y lo que hace es obtener la informacion: list va obtener el modelo del objeto jlist

        for (int i=0; i<modelo1.getSize(); i++){//getSize se obtiene el total de los elementos
            list.addElement(modelo1.getElementAt(i));//añada los elementos conforme el ciclo va avanzando
        }
        jList2.setModel(list);//al segundo jList le setiamos los elementos de list
    }//GEN-LAST:event_btn_todos_perfiles_a_AplicacionesActionPerformed

    private void btn_Quitar_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_unoActionPerformed
        /*
        String cadena;
        cadena = (String) jList2.getSelectedValue();

        list.addElement(cadena);
        jList1.setModel(list);
        */
        list.remove(jList2.getSelectedIndex());
        jList2.setModel(list);
    }//GEN-LAST:event_btn_Quitar_unoActionPerformed

    private void btn_Perfiles_A_AplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Perfiles_A_AplicacionesActionPerformed
        String cadena;
        cadena = (String) jList1.getSelectedValue();

        list.addElement(cadena);
        jList2.setModel(list);
    }//GEN-LAST:event_btn_Perfiles_A_AplicacionesActionPerformed

    private void btn_Quitar_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_TodosActionPerformed
        DefaultListModel listModel = (DefaultListModel) jList2.getModel();

        listModel.removeAllElements();
        jList2.setModel(listModel);
    }//GEN-LAST:event_btn_Quitar_TodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_cod_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cod_UsuarioActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Perfiles_A_Aplicaciones;
    private javax.swing.JButton btn_Quitar_Todos;
    private javax.swing.JButton btn_Quitar_uno;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_todos_perfiles_a_Aplicaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> txt_cod_Usuario;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
