
 
package seguridad.vista;
import seguridad.datos.PerfilDAO;
import seguridad.dominio.Perfil;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nay Ale
 */
public class MantenimientoPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form MantenimientoPerfil
     */
    public MantenimientoPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botton_Guardar = new javax.swing.JButton();
        Botton_Modificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_IdPerfil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_NombreP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_DescPerfil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCB_estado = new javax.swing.JComboBox<>();
        Botton_Borrar = new javax.swing.JButton();
        Botton_Buscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento Perfil");
        setRequestFocusEnabled(false);
        setVisible(true);

        Botton_Guardar.setBackground(new java.awt.Color(204, 204, 204));
        Botton_Guardar.setText("Guardar");
        Botton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_GuardarActionPerformed(evt);
            }
        });

        Botton_Modificar.setBackground(new java.awt.Color(204, 204, 204));
        Botton_Modificar.setText("Modificar");
        Botton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_ModificarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Id Perfil:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Perfil:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion Perfil:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Estado Pefil:");

        jCB_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Deshabilitado" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_IdPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_DescPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_IdPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_DescPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCB_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Botton_Borrar.setBackground(new java.awt.Color(204, 204, 204));
        Botton_Borrar.setText("Borrar");
        Botton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_BorrarActionPerformed(evt);
            }
        });

        Botton_Buscar.setBackground(new java.awt.Color(204, 204, 204));
        Botton_Buscar.setText("Buscar");
        Botton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Perfil", "Nombre Perfil", "Descripcion", "Estado Perfil"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Botton_Buscar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Botton_Guardar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Botton_Modificar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Botton_Borrar, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Botton_Guardar)
                                .addGap(28, 28, 28)
                                .addComponent(Botton_Modificar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(Botton_Borrar)))
                        .addGap(28, 28, 28)
                        .addComponent(Botton_Buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_GuardarActionPerformed
        PerfilDAO perfilDAO = new PerfilDAO();
        Perfil perfilesInsertar = new Perfil();
        perfilesInsertar.setIdperfil(1);
        String r1="";
        // Prueba insert
        perfilesInsertar.setIdperfil((int) Double.parseDouble(txt_IdPerfil.getText()));
        perfilesInsertar.setNombrePerfil(txt_NombreP.getText());
        perfilesInsertar.setDescripcionPerfil(txt_DescPerfil.getText());  
        perfilesInsertar.setEstadoPerfil(r1);
        r1 = jCB_estado.getSelectedItem().toString();
        if (r1.equals("")){           
        } else {
        }
        perfilDAO.insert(perfilesInsertar);
        
        // Insertamos un nuevo perfil 
        Perfil perfil = new Perfil ();
        perfilDAO.insert(perfil);
    }//GEN-LAST:event_Botton_GuardarActionPerformed

    private void Botton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_ModificarActionPerformed
         PerfilDAO perfilDAO = new PerfilDAO();
        Perfil perfilesActualizar = new Perfil();
        perfilesActualizar.setIdperfil(1);
        String r1="";
        // Prueba update
        perfilesActualizar.setIdperfil((int) Double.parseDouble(txt_IdPerfil.getText()));
        perfilesActualizar.setNombrePerfil(txt_NombreP.getText());
        perfilesActualizar.setDescripcionPerfil(txt_DescPerfil.getText());  
        perfilesActualizar.setEstadoPerfil(r1);
        r1 = jCB_estado.getSelectedItem().toString();
        if (r1.equals("")){           
        } else {
        }
        perfilDAO.update(perfilesActualizar);
    }//GEN-LAST:event_Botton_ModificarActionPerformed

    private void Botton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_BorrarActionPerformed
        PerfilDAO perfilDAO = new PerfilDAO();
        //Prueba delete
        Perfil personaEliminar = new Perfil();
       personaEliminar.setIdperfil(1);
       perfilDAO.delete(personaEliminar);
    }//GEN-LAST:event_Botton_BorrarActionPerformed

    private void Botton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_BuscarActionPerformed
    PerfilDAO perfilDAO = new PerfilDAO();
        Perfil perfilesConsultar = new Perfil();
        perfilesConsultar.setIdperfil(1);
        String r1="";
        // Prueba query
        perfilesConsultar.setIdperfil((int) Double.parseDouble(txt_IdPerfil.getText()));
        perfilesConsultar.setNombrePerfil(txt_NombreP.getText());
        perfilesConsultar.setDescripcionPerfil(txt_DescPerfil.getText());  
        perfilesConsultar.setEstadoPerfil(r1);
        r1 = jCB_estado.getSelectedItem().toString();
        if (r1.equals("")){           
        } else {
        }
        perfilDAO.query(perfilesConsultar);
         try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg?useSSL=false&serverTimezone=UTC", "root", "12345");

    PreparedStatement ps=cn.prepareStatement("select * from tbl_perfil_encabezado1");
    ResultSet rs=ps.executeQuery();
    DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
    tm.setRowCount(0);
    while(rs.next())
    {
   Object o[]={rs.getInt("Pk_id_perfil"),rs.getString("nombre_perfil"),rs.getString("descripcion_perfil"),rs.getString("estado_perfil")};
      tm.addRow(o);
    }
    }
    catch(Exception e)
    {
    JOptionPane.showMessageDialog(this,e);
    }
    }//GEN-LAST:event_Botton_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botton_Borrar;
    private javax.swing.JButton Botton_Buscar;
    private javax.swing.JButton Botton_Guardar;
    private javax.swing.JButton Botton_Modificar;
    public javax.swing.JComboBox<String> jCB_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField txt_DescPerfil;
    public javax.swing.JTextField txt_IdPerfil;
    public javax.swing.JTextField txt_NombreP;
    // End of variables declaration//GEN-END:variables
}
